{% set python_min = '3.11' %}
{% set name = "cifkit" %}
{%- set version = "1.1.1" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72bb086fa56637082d1050bf35c379f3ef6854230df426d0b86aaaf161d73aef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - gemmi
    - matplotlib-base
    - numpy
    - pyvista
    - scipy
    - setuptools
    - click
    - bobleesj.utils

test:
  imports:
    - cifkit
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pip list

about:
  home: https://github.com/bobleesj/cifkit
  summary: 'Python package for .cif high-throughput analysis'
  description: |
    cifkit is an open-source Python library for preprocessing .cif files, generating supercells, and extract features.
  license: Free To Use But Restricted
  license_file: LICENSE.rst
  doc_url: https://bobleesj.github.io/cifkit/

extra:
  recipe-maintainers:
    - bobleesj
