{% set name = "cifkit" %}
{%- set version = "1.0.4rc5" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test.pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56f3b4ef24c4193953378ee2e67ac02380269a18fd3d06cc82fee7e80ee20593

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >=3.10
    - gemmi
    - matplotlib-base
    - numpy
    - pyvista
    - scipy
    - setuptools
    - click

test:
  imports:
    - cifkit
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    - python -m pytest -m "not pyvista"

about:
  home: https://github.com/bobleesj/cifkit
  summary: 'Python package for .cif high-throughput analysis'
  description: |
    cifkit is an open-source Python library for preprocessing .cif files, generating supercells, and extract features.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://bobleesj.github.io/cifkit/

extra:
  recipe-maintainers:
    - bobleesj
