{% set python_min = '3.10' %}
{% set name = "cifkit" %}
{%- set version = "1.0.5" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b71d398d73800db32b09785af0e755e2bebb1d508fd8fa319ca16379386e98e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - gemmi
    - matplotlib-base
    - numpy
    - pyvista
    - scipy
    - setuptools
    - click

test:
  imports:
    - cifkit
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    - python -m pytest -m "not pyvista"

about:
  home: https://github.com/bobleesj/cifkit
  summary: 'Python package for .cif high-throughput analysis'
  description: |
    cifkit is an open-source Python library for preprocessing .cif files, generating supercells, and extract features.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://bobleesj.github.io/cifkit/

extra:
  recipe-maintainers:
    - bobleesj
