{% set name = "cifkit" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ddb5d97a5d784d4f8c161a53ccceab72d0f8c1016c393b71b38d286f1f9a72f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip

  run:
    - python >=3.10
    - gemmi
    - matplotlib-base
    - numpy
    - pyvista
    - scipy
    - setuptools
    - click

test:
  imports:
    - cifkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bobleesj/cifkit
  summary: 'Python package for .cif high-throughput analysis'
  description: |
    cifkit is an open-source Python library for preprocessing .cif files, generating supercells, and extract features.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://bobleesj.github.io/cifkit/

extra:
  recipe-maintainers:
    - bobleesj
